# Generated by Django 3.2.1 on 2025-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=8),
        ),
    ]
