# Generated by Django 3.2.1 on 2025-04-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='index_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='program',
            field=models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Purchasing and Supply', 'Purchasing and Supply'), ('Accountancy', 'Accountancy'), ('Computer Network Management', 'Computer Network Management'), ('Computer Science', 'Computer Science'), ('Automotive Engineering', 'Automotive Engineering'), ('Building Technology', 'Building Technology'), ('Civil Engineering', 'Civil Engineering')], max_length=27, null=True),
        ),
    ]
