# Generated by Django 3.2.1 on 2025-07-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='index_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='program',
        ),
    ]
