# Generated by Django 3.2.1 on 2025-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('index_number', models.CharField(max_length=20)),
                ('program_type', models.CharField(choices=[('hnd', 'Higher National Diploma'), ('diploma', 'Diploma'), ('btech', 'B-Tech')], max_length=7)),
                ('program', models.CharField(choices=[('computer science', 'Computer Science'), ('information technology', 'Information Technology'), ('purchasing and supply', 'Purchasing and Supply')], max_length=22)),
                ('fingerprint', models.BinaryField()),
            ],
        ),
    ]
