# Generated by Django 3.2.1 on 2025-04-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250411_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program_type',
        ),
    ]
