# Generated by Django 3.2.1 on 2025-04-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
