# Generated by Django 3.2.1 on 2025-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_session_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='program_type',
            field=models.CharField(choices=[('hnd', 'Higher National Diploma (HND)'), ('btech', 'Bachelor of Technology (BTECH)'), ('top_up', 'BTECH (Top Up)'), ('Certificate', 'certificate'), ('Diploma', 'diploma')], default='hnd', max_length=27),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='program',
            field=models.CharField(choices=[('information_technology', 'Information Technology'), ('purchasing_and_supply', 'Purchasing and Supply'), ('Accountancy', 'accountancy'), ('computer_network_Mgt', 'Computer Network Management'), ('computer_science', 'Computer Science'), ('automotive_engineering', 'Automotive Engineering'), ('building_technology', 'Building Technology'), ('civil_engineering', 'Civil Engineering')], max_length=27),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('information_technology', 'Information Technology'), ('purchasing_and_supply', 'Purchasing and Supply'), ('Accountancy', 'accountancy'), ('computer_network_Mgt', 'Computer Network Management'), ('computer_science', 'Computer Science'), ('automotive_engineering', 'Automotive Engineering'), ('building_technology', 'Building Technology'), ('civil_engineering', 'Civil Engineering')], max_length=27),
        ),
    ]
