# Generated by Django 3.2.1 on 2025-04-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20250420_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='program_type',
            field=models.CharField(choices=[('Higher National Diploma (HND)', 'Higher National Diploma (HND)'), ('Bachelor of Technology (BTECH)', 'Bachelor of Technology (BTECH)'), ('BTECH (Top Up)', 'BTECH (Top Up)'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma')], max_length=30),
        ),
    ]
