# Generated by Django 3.2.1 on 2025-04-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20250423_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created']},
        ),
    ]
