# Generated by Django 3.2.1 on 2025-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20250423_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
