# Generated by Django 3.2.1 on 2025-07-22 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_auto_20250508_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('index_number', models.CharField(max_length=20)),
                ('program', models.CharField(choices=[('Information Technology', 'Information Technology'), ('Purchasing and Supply', 'Purchasing and Supply'), ('Accountancy', 'Accountancy'), ('Computer Network Management', 'Computer Network Management'), ('Computer Science', 'Computer Science'), ('Automotive Engineering', 'Automotive Engineering'), ('Building Technology', 'Building Technology'), ('Civil Engineering', 'Civil Engineering')], max_length=27)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
