# Generated by Django 3.2.1 on 2025-07-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default='Level 100', max_length=10),
            preserve_default=False,
        ),
    ]
